name: CI-CD

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando o usuário no Docker
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Contruindo a imagem e enviando para o Docker Hub
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            m4rlonalvesilva/kube-news:latest
            m4rlonalvesilva/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Definindo o Kube config
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Efetuando o deploy no Kubernetes
        uses: Azure/k8s-deploy@v3.1
        with:
          images: m4rlonalvesilva/kube-news:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml